name: Build and push images to Quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'

jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "7.3/Dockerfile"
            docker_context: "7.3"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
            image_name: "php-73-centos7"

          - dockerfile: "7.4/Dockerfile"
            docker_context: "7.4"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
            image_name: "php-74-centos7"

          - dockerfile: "7.4/Dockerfile.c9s"
            docker_context: "7.4"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "php-74-c9s"

          - dockerfile: "8.0/Dockerfile.fedora"
            docker_context: "8.0"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "8.0"
            image_name: "php-80"

          - dockerfile: "8.1/Dockerfile.fedora"
            docker_context: "8.1"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "8.1"
            image_name: "php-81"

    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          docker_context: ${{ matrix.docker_context }}
          tag: ${{ matrix.tag }}
          image_name: ${{ matrix.image_name }}
